CREATE TABLE IF NOT EXISTS Users (
  id TEXT PRIMARY KEY UNIQUE,
  username TEXT NOT NULL UNIQUE,
  passKey TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Stars (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  imageId TEXT REFERENCES Images(id),
  starReviewCount INTEGER CHECK (starReviewCount BETWEEN 1 AND 5)
);

CREATE TABLE IF NOT EXISTS Images (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userId TEXT REFERENCES Users(id),
  imageLocation TEXT
);

CREATE TABLE IF NOT EXISTS Comments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  imageId TEXT REFERENCES Images(id),
  comment TEXT
);
